USE ROLE ACCOUNTADMIN;

-- 1. Create roles
CREATE OR REPLACE ROLE QA_READONLY;

-- 2. Grant warehouse access
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE QA_READONLY;

-- 3. Grant database access
GRANT USAGE ON DATABASE DEV_LANDING_ADF TO ROLE QA_READONLY;

-- 4. Grant schema access
GRANT USAGE ON ALL SCHEMAS IN DATABASE DEV_LANDING_ADF TO ROLE QA_READONLY;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE DEV_LANDING_ADF TO ROLE QA_READONLY;

-- 5. Grant table access
GRANT SELECT ON ALL TABLES IN DATABASE DEV_LANDING_ADF TO ROLE QA_READONLY;
GRANT SELECT ON FUTURE TABLES IN DATABASE DEV_LANDING_ADF TO ROLE QA_READONLY;

-- 6. Grant view access
GRANT SELECT ON ALL VIEWS IN DATABASE DEV_LANDING_ADF TO ROLE QA_READONLY;
GRANT SELECT ON FUTURE VIEWS IN DATABASE DEV_LANDING_ADF TO ROLE QA_READONLY;

-- 7. Grant role to SYSADMIN & USER
GRANT ROLE QA_READONLY TO ROLE SYSADMIN;
GRANT ROLE QA_READONLY TO USER ARUDSEKABERNESNOWEXP3;