-- 1. Set current role
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;

-- 2. Remove masking policy if tagged
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBListings"
MODIFY COLUMN "name" UNSET MASKING POLICY
;

-- 3. Create new masking policy
-- DROP MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_LISTINGS_MASKING_POLICY;
CREATE OR REPLACE MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_LISTINGS_MASKING_POLICY AS (PII_VALUE STRING, ROOM_TYPE STRING)
RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN') THEN PII_VALUE
        WHEN CURRENT_ROLE() IN ('BI_READONLY') THEN 
            -- CONDITIONAL MASKING
            CASE
                WHEN LOWER(ROOM_TYPE) = 'private room' THEN REGEXP_REPLACE(PII_VALUE, '(.{1}).', '\\1*')
                ELSE REGEXP_REPLACE(PII_VALUE, '(.{4}).', '\\1*')
            END
        ELSE '*** MASKED ***'
    END
;

-- 4. Validate masking policy creation
SELECT GET_DDL('POLICY', 'DEV_LANDING_ADF.AIRBNB.PII_LISTINGS_MASKING_POLICY');

-- 5. Tag masking policy
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBListings"
MODIFY COLUMN "name"
SET MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_LISTINGS_MASKING_POLICY
    USING("name", "room_type")
;

-- 6. Full access
USE ROLE SYSADMIN;
SELECT "room_type", "name" FROM DEV_LANDING_ADF.AIRBNB."AirBnBListings" LIMIT 5;

-- 7. Partial access (conditional basis)
USE ROLE BI_READONLY;
SELECT "room_type", "name" FROM DEV_LANDING_ADF.AIRBNB."AirBnBListings" LIMIT 5;

-- 8. No access
USE ROLE QA_READONLY;
SELECT "room_type", "name" FROM DEV_LANDING_ADF.AIRBNB."AirBnBListings" LIMIT 5;
