-- 1. Set current role
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;

-- 2. Remove masking policy if tagged
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBDrivers"
MODIFY COLUMN PAYLOAD UNSET MASKING POLICY
;

-- 3. Create new masking policy
-- DROP MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_MASKING_POLICY;
CREATE OR REPLACE MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_MASKING_POLICY AS (PAYLOAD VARIANT)
RETURNS VARIANT ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN') THEN PAYLOAD
        WHEN CURRENT_ROLE() IN ('BI_READONLY') THEN 
            -- CONDITIONAL MASKING
            CASE
                WHEN LOWER(PAYLOAD:nationality) = 'british' THEN
                     OBJECT_INSERT(PAYLOAD, 'name', OBJECT_INSERT(PAYLOAD:name, 'forename', '*** FORENAME-MASKED ***', TRUE), TRUE)
                ELSE OBJECT_INSERT(PAYLOAD, 'name', OBJECT_INSERT(PAYLOAD:name, 'surname', '*** SURNAME-MASKED ***', TRUE), TRUE)
            END
        ELSE OBJECT_INSERT(PAYLOAD, 'name', '*** MASKED ***', TRUE)
    END
;

-- 4. Validate masking policy creation
SELECT GET_DDL('POLICY', 'DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_MASKING_POLICY');

-- 5. Tag masking policy
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBDrivers"
MODIFY COLUMN PAYLOAD
SET MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_MASKING_POLICY
;

-- 6. Full access
USE ROLE SYSADMIN;
SELECT PAYLOAD:nationality, PAYLOAD:name, PAYLOAD:name:forename, PAYLOAD:name:surname FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" LIMIT 5;

-- 7. Partial access (conditional basis)
USE ROLE BI_READONLY;
SELECT PAYLOAD:nationality, PAYLOAD:name, PAYLOAD:name:forename, PAYLOAD:name:surname FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" LIMIT 5;

-- 8. No access
USE ROLE QA_READONLY;
SELECT PAYLOAD:nationality, PAYLOAD:name, PAYLOAD:name:forename, PAYLOAD:name:surname FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" LIMIT 5;
