-- 1. Set current role
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;

-- 2. Remove masking policy if tagged
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBDrivers"
DROP ALL ROW ACCESS POLICIES
;

-- 3. Create new masking policy
-- DROP ROW ACCESS POLICY DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_ACCESS_POLICY;
CREATE OR REPLACE ROW ACCESS POLICY DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_ACCESS_POLICY AS (PAYLOAD VARIANT)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN', 'SYSADMIN') THEN TRUE
        WHEN CURRENT_ROLE() IN ('BI_READONLY') AND LOWER(PAYLOAD:nationality) = 'british' THEN TRUE
        ELSE FALSE
    END
;

-- 4. Validate masking policy creation
SELECT GET_DDL('POLICY', 'DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_ACCESS_POLICY');

-- 5. Tag masking policy
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBDrivers"
ADD ROW ACCESS POLICY DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_ACCESS_POLICY
    ON(PAYLOAD)
;
-- 6. Full access
USE ROLE SYSADMIN;
SELECT PAYLOAD:nationality, PAYLOAD:name FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" ORDER BY 1;

-- 7. Partial access (conditional basis)
USE ROLE BI_READONLY;
SELECT PAYLOAD:nationality, PAYLOAD:name FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" ORDER BY 1;

-- 8. No access
USE ROLE QA_READONLY;
SELECT PAYLOAD:nationality, PAYLOAD:name FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" ORDER BY 1;
