-- 1. Set current role
USE ROLE ACCOUNTADMIN;
USE SECONDARY ROLES NONE;

-- 2. Remove masking policy if tagged
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBDrivers"
DROP ALL ROW ACCESS POLICIES
;

-- 3. Create masking logic
-- DROP FUNCTION IF EXISTS DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_ACCESS_LOGIC(VARCHAR, VARIANT);
CREATE OR REPLACE FUNCTION DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_ACCESS_LOGIC(ROLE VARCHAR, PAYLOAD VARIANT)
RETURNS BOOLEAN
LANGUAGE PYTHON
RUNTIME_VERSION = 3.10
HANDLER = 'mask_handler'
AS
$$
def mask_handler(role: str, payload: dict) -> bool:
    # payload arrives as a Python dict if variant is JSON-like

    if role in ("ACCOUNTADMIN", "SYSADMIN"):
        return True
        
    elif role in ("BI_READONLY"):
        if payload["nationality"].lower() == "british":
            return True

    return False
$$;

-- 4. Create new masking policy
-- DROP ROW ACCESS POLICY DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_ACCESS_POLICY;
CREATE OR REPLACE ROW ACCESS POLICY DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_ACCESS_POLICY AS (PAYLOAD VARIANT)
RETURNS BOOLEAN ->
    DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_ACCESS_LOGIC(CURRENT_ROLE(), PAYLOAD)
;

-- 4. Validate masking policy creation
SELECT GET_DDL('POLICY', 'DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_ACCESS_POLICY');

-- 5. Tag masking policy
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBDrivers"
ADD ROW ACCESS POLICY DEV_LANDING_ADF.AIRBNB.PII_DRIVERS_ACCESS_POLICY
    ON(PAYLOAD)
;
-- 6. Full access
USE ROLE SYSADMIN;
SELECT DISTINCT PAYLOAD:nationality FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" ORDER BY 1;

-- 7. Partial access (conditional basis)
USE ROLE BI_READONLY;
SELECT DISTINCT PAYLOAD:nationality FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" ORDER BY 1;

-- 8. No access
USE ROLE QA_READONLY;
SELECT DISTINCT PAYLOAD:nationality FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" ORDER BY 1;
