-- 1. Set current role
USE ROLE ACCOUNTADMIN;

-- 2. Cleanup
ALTER TAG DEV_LANDING_ADF.AIRBNB.PII_TAG
UNSET MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY;

DROP TAG IF EXISTS DEV_LANDING_ADF.AIRBNB.PII_TAG;
DROP MASKING POLICY IF EXISTS DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY;

DROP VIEW IF EXISTS DEV_LANDING_ADF.AIRBNB."v_AirBnBListings";
DROP MATERIALIZED VIEW IF EXISTS DEV_LANDING_ADF.AIRBNB."mv_AirBnBListings";
DROP VIEW IF EXISTS DEV_LANDING_ADF.AIRBNB."sv_AirBnBListings";
DROP TABLE IF EXISTS DEV_LANDING_ADF.AIRBNB."ctas_AirBnBListings";
DROP TABLE IF EXISTS DEV_LANDING_ADF.AIRBNB."ctlike_AirBnBListings";
DROP TABLE IF EXISTS DEV_LANDING_ADF.AIRBNB."ctclone_AirBnBListings";

-- 3. Create TAG
CREATE OR REPLACE TAG DEV_LANDING_ADF.AIRBNB.PII_TAG
PROPAGATE = ON_DEPENDENCY_AND_DATA_MOVEMENT;

-- 4. Create MASKING POLICY
CREATE OR REPLACE MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY
AS (PII_VALUE STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN PII_VALUE
        ELSE '*** MASKED ***'
    END
;

-- 5. Assign MASKING POLICY to TAG
ALTER TAG DEV_LANDING_ADF.AIRBNB.PII_TAG
SET MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY;

-- 6. Assign TAG to COLUMN
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBListings"
MODIFY COLUMN "name"
SET TAG DEV_LANDING_ADF.AIRBNB.PII_TAG = 'name';

-- 7. Validate data masking
USE ROLE SYSADMIN;
SELECT * FROM DEV_LANDING_ADF.AIRBNB."AirBnBListings"
LIMIT 5;

-- 8. Create view and validate data masking (MASKED without PROP)
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE VIEW DEV_LANDING_ADF.AIRBNB."v_AirBnBListings" AS
SELECT * FROM DEV_LANDING_ADF.AIRBNB."AirBnBListings";

USE ROLE SYSADMIN;
SELECT * FROM DEV_LANDING_ADF.AIRBNB."v_AirBnBListings" LIMIT 5;

-- 9. Create materialized view and validate data masking (RESTRICTED)
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE MATERIALIZED VIEW DEV_LANDING_ADF.AIRBNB."mv_AirBnBListings" AS
SELECT * FROM DEV_LANDING_ADF.AIRBNB."AirBnBListings";

-- 10. Create secure view and validate data masking  (MASKED without PROP)
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE SECURE VIEW DEV_LANDING_ADF.AIRBNB."sv_AirBnBListings" AS
SELECT * FROM DEV_LANDING_ADF.AIRBNB."AirBnBListings";

USE ROLE SYSADMIN;
SELECT * FROM DEV_LANDING_ADF.AIRBNB."sv_AirBnBListings";

-- 11. Create CTAS and validate data masking  (MASKED with PROP)
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE TABLE DEV_LANDING_ADF.AIRBNB."ctas_AirBnBListings" AS
SELECT * FROM DEV_LANDING_ADF.AIRBNB."AirBnBListings";

USE ROLE SYSADMIN;
SELECT * FROM DEV_LANDING_ADF.AIRBNB."ctas_AirBnBListings";

-- 11. Create CREATE TABLE LIKE and validate data masking  (MASKED without PROP)
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE TABLE DEV_LANDING_ADF.AIRBNB."ctlike_AirBnBListings" 
LIKE DEV_LANDING_ADF.AIRBNB."AirBnBListings";

INSERT INTO DEV_LANDING_ADF.AIRBNB."ctlike_AirBnBListings" 
    SELECT * FROM DEV_LANDING_ADF.AIRBNB."AirBnBListings";

USE ROLE SYSADMIN;
SELECT * FROM DEV_LANDING_ADF.AIRBNB."ctlike_AirBnBListings";

-- 12. Create CREATE TABLE CLONE and validate data masking  (MASKED without PROP)
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE TABLE DEV_LANDING_ADF.AIRBNB."ctclone_AirBnBListings" 
CLONE DEV_LANDING_ADF.AIRBNB."AirBnBListings";

USE ROLE SYSADMIN;
SELECT * FROM DEV_LANDING_ADF.AIRBNB."ctclone_AirBnBListings";