-- 1. Landing tables
CREATE OR REPLACE TABLE DEV_LANDING_ADF.AIRBNB."AirBnBListings"(
    SYSLOADDATE TIMESTAMP_LTZ NOT NULL,
    SYSRUNID VARCHAR NOT NULL,
    SYSPROCESSINGTOOL VARCHAR NOT NULL,
    SYSDATAPROCESSORNAME VARCHAR NOT NULL,
    SOURCESYSTEM VARCHAR NOT NULL,
    "id" VARCHAR,
    "name" VARCHAR,
    "host_id" VARCHAR,
    "host_name" VARCHAR,
    "neighbourhood_group" VARCHAR,
    "neighbourhood" VARCHAR,
    "latitude" VARCHAR,
    "longitude" VARCHAR,
    "room_type" VARCHAR,
    "price" VARCHAR,
    "minimum_nights" VARCHAR,
    "number_of_reviews" VARCHAR,
    "last_review" VARCHAR,
    "reviews_per_month" VARCHAR,
    "calculated_host_listings_count" VARCHAR,
    "availability_365" VARCHAR,
    "number_of_reviews_ltm" VARCHAR,
    "license" VARCHAR
);

CREATE OR REPLACE TABLE DEV_LANDING_ADF.AIRBNB."AirBnBReviews"(
    SYSLOADDATE TIMESTAMP_LTZ NOT NULL,
    SYSRUNID VARCHAR NOT NULL,
    SYSPROCESSINGTOOL VARCHAR NOT NULL,
    SYSDATAPROCESSORNAME VARCHAR NOT NULL,
    SOURCESYSTEM VARCHAR NOT NULL,
    "listing_id" VARCHAR,
    "id" VARCHAR,
    "date" VARCHAR,
    "reviewer_id" VARCHAR,
    "reviewer_name" VARCHAR,
    "comments" VARCHAR
);

CREATE OR REPLACE TABLE DEV_LANDING_ADF.AIRBNB."AirBnBDrivers"(
    PAYLOAD VARIANT NOT NULL
);

-- 2. Gold tables
CREATE OR REPLACE TABLE DEV_GOLD_ADF.AIRBNB.DIM_GEOGRAPHY(
    GEOGRAPHY_ID NUMBER(38,0) AUTOINCREMENT,
    BOROUGH_ID NUMBER(38,0),
    LATITUDE NUMBER(10,8),
    LONGITUDE NUMBER(11,8),
    GEO_POINT GEOGRAPHY,
    NEIGHBOURHOOD VARCHAR(100),
    NEIGHBOURHOOD_GROUP VARCHAR(100),
    CITY VARCHAR(50),
    COUNTRY_CODE CHAR(2),
    ZIPCODE VARCHAR(20),
    PRIMARY KEY(GEOGRAPHY_ID)
);

INSERT OVERWRITE INTO DEV_GOLD_ADF.AIRBNB.DIM_GEOGRAPHY
    (GEOGRAPHY_ID, BOROUGH_ID, LATITUDE, LONGITUDE, GEO_POINT, NEIGHBOURHOOD, NEIGHBOURHOOD_GROUP, CITY, COUNTRY_CODE, ZIPCODE) VALUES
    (1, 101, 51.56861000, -0.11270000, NULL, 'NEIGHBOURHOOD A', 'BOROUGH A', 'LONDON', 'GB', 'N/A'),
    (2, 102, 51.47072000, -0.16266000, NULL, 'NEIGHBOURHOOD B', 'BOROUGH B', 'LONDON', 'GB', 'N/A'),
    (3, 103, 51.50701000, -0.23362000, NULL, 'NEIGHBOURHOOD C', 'BOROUGH C', 'LONDON', 'GB', 'N/A'),
    (4, 104, 51.61492000, -0.25632000, NULL, 'NEIGHBOURHOOD D', 'BOROUGH D', 'LONDON', 'GB', 'N/A'),
    (5, 105, 51.52958000, -0.14344000, NULL, 'NEIGHBOURHOOD E', 'BOROUGH E', 'LONDON', 'GB', 'N/A'),
    (6, 106, 51.39648000, -0.21170000, NULL, 'NEIGHBOURHOOD F', 'BOROUGH F', 'LONDON', 'GB', 'N/A')
;


CREATE OR REPLACE TABLE DEV_GOLD_ADF.AIRBNB.DIM_GEOGRAPHY_GEOSPATIAL(
    GEOSPATIAL_ID NUMBER(38,0) AUTOINCREMENT,
    GEOGRAPHY_ID NUMBER(38,0),
    WARD_ID NUMBER(38,0),
    LOCATION_NAME VARCHAR(100),
    DESCRIPTION VARCHAR(255),
    LATITUDE NUMBER(10,8),
    LONGITUDE NUMBER(11,8),
    GEO_POINT GEOGRAPHY,
    COUNTRY_CODE CHAR(2),
    CITY VARCHAR(50),
    ZIPCODE VARCHAR(20),
    PRIMARY KEY(GEOSPATIAL_ID)
);


INSERT OVERWRITE INTO DEV_GOLD_ADF.AIRBNB.DIM_GEOGRAPHY_GEOSPATIAL
    (GEOSPATIAL_ID, GEOGRAPHY_ID, WARD_ID, LOCATION_NAME, DESCRIPTION, LATITUDE, LONGITUDE, GEO_POINT, COUNTRY_CODE, CITY, ZIPCODE) VALUES
    (1, 1, 2001, 'LOCATION A PARK', 'Area in North London', 51.56861000, -0.11270000, NULL, 'GB', 'LONDON', 'N/A'),
    (2, 2, 2002, 'LOCATION B STREET', 'Residential street', 51.47072000, -0.16266000, NULL, 'GB', 'LONDON', 'N/A'),
    (3, 3, 2003, 'LOCATION C MARKET', 'Local market area', 51.50701000, -0.23362000, NULL, 'GB', 'LONDON', 'N/A'),
    (4, 4, 2004, 'LOCATION D HILL', 'Northern hill region', 51.61492000, -0.25632000, NULL, 'GB', 'LONDON', 'N/A'),
    (5, 5, 2005, 'LOCATION E SQUARE', 'Central square area', 51.52958000, -0.14344000, NULL, 'GB', 'LONDON', 'N/A'),
    (6, 6, 2006, 'LOCATION F PARK', 'South-west open area', 51.39648000, -0.21170000, NULL, 'GB', 'LONDON', 'N/A')
; 
