-- 1. Cleanup
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBListings" MODIFY COLUMN "host_name" UNSET MASKING POLICY;
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" MODIFY COLUMN PAYLOAD UNSET MASKING POLICY;
DROP MASKING POLICY IF EXISTS DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_LISTINGS;
DROP MASKING POLICY IF EXISTS DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_DRIVERS;


-- 2. Create MASKING POLICYs
CREATE OR REPLACE MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_LISTINGS
AS (PII_VALUE STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN PII_VALUE
        ELSE '*** COLUMN MASK ***'
    END
;

CREATE OR REPLACE MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_DRIVERS AS (PAYLOAD VARIANT)
RETURNS VARIANT ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN PAYLOAD
        ELSE OBJECT_INSERT(PAYLOAD, 'name', OBJECT_INSERT(PAYLOAD:name, 'forename', '*** FIELD MASK ***', TRUE), TRUE)
    END
;

-- CREATE OR REPLACE MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_DRIVERS AS (PAYLOAD VARIANT)
-- RETURNS VARIANT ->
--     CASE
--         WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN PAYLOAD
--         ELSE TO_VARIANT('*** PAYLOAD MASK ***')
--     END
-- ;


-- 3. SET TAG at different object
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBListings" MODIFY COLUMN "name" SET MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_LISTINGS;
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" MODIFY COLUMN PAYLOAD SET MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_DRIVERS;