-- 1. Cleanup
ALTER TAG DEV_LANDING_ADF.AIRBNB.PII_TAG_REVIEWS UNSET MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_REVIEWS;
ALTER TAG DEV_LANDING_ADF.AIRBNB."PII_TAG_LISTINGs" UNSET MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_LISTINGS;
ALTER TAG DEV_LANDING_ADF.AIRBNB.PII_TAG_DRIVERS UNSET MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_DRIVERS;
DROP TAG IF EXISTS DEV_LANDING_ADF.AIRBNB.PII_TAG_REVIEWS;
DROP TAG IF EXISTS DEV_LANDING_ADF.AIRBNB."PII_TAG_LISTINGs";
DROP TAG IF EXISTS DEV_LANDING_ADF.AIRBNB.PII_TAG_DRIVERS;
DROP MASKING POLICY IF EXISTS DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_REVIEWS;
DROP MASKING POLICY IF EXISTS DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_LISTINGS;
DROP MASKING POLICY IF EXISTS DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_DRIVERS;


-- 2. Create TAGs
CREATE OR REPLACE TAG DEV_LANDING_ADF.AIRBNB.PII_TAG_REVIEWS;
CREATE OR REPLACE TAG DEV_LANDING_ADF.AIRBNB."PII_TAG_LISTINGs";
CREATE OR REPLACE TAG DEV_LANDING_ADF.AIRBNB.PII_TAG_DRIVERS;
-- CREATE OR REPLACE TAG DEV_LANDING_ADF.AIRBNB.PII_TAG_REVIEWS PROPAGATE = ON_DEPENDENCY_AND_DATA_MOVEMENT;
-- CREATE OR REPLACE TAG DEV_LANDING_ADF.AIRBNB."PII_TAG_LISTINGs" PROPAGATE = ON_DEPENDENCY_AND_DATA_MOVEMENT;
-- CREATE OR REPLACE TAG DEV_LANDING_ADF.AIRBNB.PII_TAG_DRIVERS PROPAGATE = ON_DEPENDENCY_AND_DATA_MOVEMENT;


-- 3. Create MASKING POLICYs
CREATE OR REPLACE MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_REVIEWS
AS (PII_VALUE STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN PII_VALUE
        ELSE '*** TABLE MASK ***'
    END
;

CREATE OR REPLACE MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_LISTINGS
AS (PII_VALUE STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN PII_VALUE
        ELSE '*** COLUMN MASK ***'
    END
;

CREATE OR REPLACE MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_DRIVERS AS (PAYLOAD VARIANT)
RETURNS VARIANT ->
    CASE
        WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN PAYLOAD
        ELSE OBJECT_INSERT(PAYLOAD, 'name', OBJECT_INSERT(PAYLOAD:name, 'forename', '*** FIELD MASK ***', TRUE), TRUE)
    END
;

-- CREATE OR REPLACE MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_DRIVERS AS (PAYLOAD VARIANT)
-- RETURNS VARIANT ->
--     CASE
--         WHEN CURRENT_ROLE() IN ('ACCOUNTADMIN') THEN PAYLOAD
--         ELSE TO_VARIANT('*** PAYLOAD MASK ***')
--     END
-- ;


-- 4. Tag MASKING POLICY with TAGS
ALTER TAG DEV_LANDING_ADF.AIRBNB.PII_TAG_REVIEWS SET MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_REVIEWS;
ALTER TAG DEV_LANDING_ADF.AIRBNB."PII_TAG_LISTINGs" SET MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_LISTINGS;
ALTER TAG DEV_LANDING_ADF.AIRBNB.PII_TAG_DRIVERS SET MASKING POLICY DEV_LANDING_ADF.AIRBNB.PII_MASKING_POLICY_DRIVERS;


-- 5. SET TAG at different object
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBReviews" SET TAG DEV_LANDING_ADF.AIRBNB.PII_TAG_REVIEWS = 'sensitive';
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBListings" MODIFY COLUMN "name" SET TAG DEV_LANDING_ADF.AIRBNB."PII_TAG_LISTINGs" = 'sensitive';
ALTER TABLE DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" MODIFY COLUMN PAYLOAD SET TAG DEV_LANDING_ADF.AIRBNB.PII_TAG_DRIVERS = 'sensitive';