-- 1. Drop bronze, silver, and gold schema
-- TRUNCATE TABLE DEV_LANDING_ADF.AIRBNB."AirBnBListings";
-- TRUNCATE TABLE DEV_LANDING_ADF.AIRBNB."AirBnBReviews";
-- TRUNCATE TABLE DEV_LANDING_ADF.AIRBNB."AirBnBDrivers";
DROP SCHEMA IF EXISTS DEV_BRONZE_ADF.AIRBNB;
DROP SCHEMA IF EXISTS DEV_SILVER_ADF.AIRBNB;
DROP TABLE IF EXISTS DEV_GOLD_ADF.AIRBNB.DIM_AIRBNBLISTING_DETAILS;
DROP TABLE IF EXISTS DEV_GOLD_ADF.AIRBNB.FACT_AIRBNBLISTINGS;
DROP SCHEMA IF EXISTS DEV_PLATINUM_ADF.AIRBNB;


-- 2. Update landing table (Only for silver & gold table testings)
UPDATE DEV_LANDING_ADF.AIRBNB."AirBnBListings"
SET "name" = 'Small Studio in Nottinghill gate 3'
WHERE CAST("id" AS INT) = 1000023182097063235
;

SELECT "id", "name" FROM DEV_LANDING_ADF.AIRBNB."AirBnBListings"
WHERE CAST("id" AS INT) = 1000023182097063235
;


-- 3. Execute DBT
--select +path:models/bronze_adf/airbnb
--select +path:models/bronze_adf/airbnb/airbnb_bronze_drivers.sql
--select +path:snapshots/silver/airbnb/airbnb_silver_listings.sql
--select +path:snapshots/silver/airbnb/airbnb_silver_reviews.sql
--select +path:models/gold/airbnb/airbnb_gold_fact_listings.sql


-- 4. Validate table level masking
USE ROLE ACCOUNTADMIN;
USE ROLE SYSADMIN;

SELECT * FROM DEV_LANDING_ADF.AIRBNB."AirBnBReviews" LIMIT 5;
SELECT * FROM DEV_BRONZE_ADF.AIRBNB."AirBnBReviews" LIMIT 5;
SELECT * FROM DEV_SILVER_ADF.AIRBNB."AirBnBReviews" LIMIT 5;


-- 5. Validate column level masking
USE ROLE ACCOUNTADMIN;
USE ROLE SYSADMIN;

SELECT "id", "name" FROM DEV_LANDING_ADF.AIRBNB."AirBnBListings"
WHERE "id" = '1000023182097063235'
;

SELECT "id", "name" FROM DEV_BRONZE_ADF.AIRBNB."AirBnBListings"
WHERE "id" = 1000023182097063235
;

SELECT "id", "name", DBT_VALID_FROM, DBT_VALID_TO FROM DEV_SILVER_ADF.AIRBNB."AirBnBListings"
WHERE "id" = 1000023182097063235
ORDER BY "id", DBT_VALID_TO
;

SELECT ID, NAME, LAST_MODIFIED_AT FROM DEV_GOLD_ADF.AIRBNB.DIM_AIRBNBLISTING_DETAILS
WHERE ID = 1000023182097063235
ORDER BY ID, LAST_MODIFIED_AT
;

SELECT LISTING_ID, LISTINGS, LAST_MODIFIED_AT FROM DEV_GOLD_ADF.AIRBNB.FACT_AIRBNBLISTINGS
WHERE LISTING_ID = 1000023182097063235
ORDER BY LISTING_ID, LAST_MODIFIED_AT
;


-- 6. Validate table field masking (SNOWFLAKE LIMITATION only for table)
USE ROLE ACCOUNTADMIN;
USE ROLE SYSADMIN;

SELECT * FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" LIMIT 5;
SELECT * FROM DEV_BRONZE_ADF.AIRBNB."AirBnBDrivers" LIMIT 5;

-- Check (Table)
DROP TABLE IF EXISTS DEV_LANDING_ADF.AIRBNB."AirBnBDrivers_Sf";
CREATE OR REPLACE TABLE DEV_LANDING_ADF.AIRBNB."AirBnBDrivers_Sf" AS
    SELECT PAYLOAD:name:forename :: STRING AS FORENAME FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" LIMIT 5;

SELECT * FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers_Sf";

-- Check (View)
DROP VIEW IF EXISTS DEV_LANDING_ADF.AIRBNB."v_AirBnBDrivers_Sf";
CREATE OR REPLACE VIEW DEV_LANDING_ADF.AIRBNB."v_AirBnBDrivers_Sf" AS
    SELECT PAYLOAD:name:forename :: STRING AS FORENAME FROM DEV_LANDING_ADF.AIRBNB."AirBnBDrivers" LIMIT 5;

SELECT * FROM DEV_LANDING_ADF.AIRBNB."v_AirBnBDrivers_Sf";