-- 1. Create schema
CREATE SCHEMA IF NOT EXISTS DEV_LANDING_ADF.CONFIG;

-- 2. Create config tables and views (used my ADF pipeline)
CREATE OR REPLACE TABLE DEV_LANDING_ADF.CONFIG.SOURCE_LANDING_JOB_METADATA (
    JOB_ID INT PRIMARY KEY,
    SOURCE_NAME VARCHAR UNIQUE NOT NULL,
    SINK_SCHEMA VARCHAR NOT NULL
);

CREATE OR REPLACE TABLE DEV_LANDING_ADF.CONFIG.SOURCE_LANDING_TASK_METADATA (
    JOB_ID INT,
    TASK_ID INT,
    TASK_SWITCH VARCHAR NOT NULL,
    SOURCE_CONFIG VARIANT NOT NULL,
    SINK_TABLE VARCHAR NOT NULL,
    PRIMARY KEY (JOB_ID, TASK_ID),
    FOREIGN KEY (JOB_ID) REFERENCES DEV_LANDING_ADF.CONFIG.SOURCE_LANDING_JOB_METADATA(JOB_ID)
);

CREATE OR REPLACE VIEW DEV_LANDING_ADF.CONFIG.V_SOURCE_LANDING_TASK_METADATA AS
SELECT
    job.JOB_ID,
    task.TASK_ID,
    task.TASK_SWITCH,
    job.SOURCE_NAME,
    task.SOURCE_CONFIG,
    'DEV_LANDING_ADF' AS SINK_DATABASE,
    UPPER(TRIM(job.SINK_SCHEMA)) AS SINK_SCHEMA,
    TRIM(task.SINK_TABLE) AS SINK_TABLE
FROM DEV_LANDING_ADF.CONFIG.SOURCE_LANDING_JOB_METADATA AS job
INNER JOIN DEV_LANDING_ADF.CONFIG.SOURCE_LANDING_TASK_METADATA AS task
    USING(JOB_ID)
ORDER BY task.TASK_ID
;

-- 3. Insert config values
INSERT OVERWRITE INTO DEV_LANDING_ADF.CONFIG.SOURCE_LANDING_JOB_METADATA
SELECT 1, 'Airbnb', 'AIRBNB'
;

INSERT OVERWRITE INTO DEV_LANDING_ADF.CONFIG.SOURCE_LANDING_TASK_METADATA
SELECT 1, 1, 'BLOB_CSV',
    PARSE_JSON('{"container": "sources", "folder": "airbnb", "file": "listings.csv", "delimiter": ",", "header": true}'),
    'AirBnBListings'
UNION ALL SELECT
    1, 2, 'ADLS_CSV',
    PARSE_JSON('{"container": "sources", "folder": "airbnb", "file": "reviews.csv.gz", "delimiter": ",", "header": true, "compression_type": "gzip"}'),
    'AirBnBReviews'
;

-- 4. View configurations
SELECT * FROM DEV_LANDING_ADF.CONFIG.SOURCE_LANDING_JOB_METADATA;
SELECT * FROM DEV_LANDING_ADF.CONFIG.SOURCE_LANDING_TASK_METADATA;

SELECT * FROM DEV_LANDING_ADF.CONFIG.V_SOURCE_LANDING_TASK_METADATA
WHERE JOB_ID = 1
;