-- ============================================================================
-- Quick Setup Script Generator for All Environments
-- ============================================================================
-- Use this script to generate setup scripts for TEST, PREPROD, and PROD
-- Simply run each section separately for each environment
-- ============================================================================

-- ============================================================================
-- TEST ENVIRONMENT
-- ============================================================================
-- Replace DEV with TEST in the dev_environment_setup.sql script

-- Quick commands:
CREATE DATABASE IF NOT EXISTS TEST_LANDING_ADF;
CREATE DATABASE IF NOT EXISTS TEST_BRONZE_ADF;
CREATE DATABASE IF NOT EXISTS TEST_SILVER;
CREATE DATABASE IF NOT EXISTS TEST_GOLD_ADF;
CREATE DATABASE IF NOT EXISTS TEST_PLATINUM;

GRANT USAGE, CREATE SCHEMA ON DATABASE TEST_LANDING_ADF TO ROLE DBT_TEST_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE TEST_BRONZE_ADF TO ROLE DBT_TEST_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE TEST_SILVER TO ROLE DBT_TEST_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE TEST_GOLD_ADF TO ROLE DBT_TEST_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE TEST_PLATINUM TO ROLE DBT_TEST_ROLE;

CREATE SCHEMA IF NOT EXISTS TEST_LANDING_ADF.AIRBNB;
CREATE SCHEMA IF NOT EXISTS TEST_GOLD_ADF.AIRBNB;

GRANT ALL PRIVILEGES ON SCHEMA TEST_LANDING_ADF.AIRBNB TO ROLE DBT_TEST_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA TEST_GOLD_ADF.AIRBNB TO ROLE DBT_TEST_ROLE;

-- Then run the table creation scripts from dev_environment_setup.sql, replacing DEV with TEST

-- ============================================================================
-- PREPROD ENVIRONMENT
-- ============================================================================

CREATE DATABASE IF NOT EXISTS PREPROD_LANDING_ADF;
CREATE DATABASE IF NOT EXISTS PREPROD_BRONZE_ADF;
CREATE DATABASE IF NOT EXISTS PREPROD_SILVER;
CREATE DATABASE IF NOT EXISTS PREPROD_GOLD_ADF;
CREATE DATABASE IF NOT EXISTS PREPROD_PLATINUM;

GRANT USAGE, CREATE SCHEMA ON DATABASE PREPROD_LANDING_ADF TO ROLE DBT_PREPROD_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE PREPROD_BRONZE_ADF TO ROLE DBT_PREPROD_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE PREPROD_SILVER TO ROLE DBT_PREPROD_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE PREPROD_GOLD_ADF TO ROLE DBT_PREPROD_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE PREPROD_PLATINUM TO ROLE DBT_PREPROD_ROLE;

CREATE SCHEMA IF NOT EXISTS PREPROD_LANDING_ADF.AIRBNB;
CREATE SCHEMA IF NOT EXISTS PREPROD_GOLD_ADF.AIRBNB;

GRANT ALL PRIVILEGES ON SCHEMA PREPROD_LANDING_ADF.AIRBNB TO ROLE DBT_PREPROD_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA PREPROD_GOLD_ADF.AIRBNB TO ROLE DBT_PREPROD_ROLE;

-- ============================================================================
-- PROD ENVIRONMENT
-- ============================================================================

CREATE DATABASE IF NOT EXISTS PROD_LANDING_ADF;
CREATE DATABASE IF NOT EXISTS PROD_BRONZE_ADF;
CREATE DATABASE IF NOT EXISTS PROD_SILVER;
CREATE DATABASE IF NOT EXISTS PROD_GOLD_ADF;
CREATE DATABASE IF NOT EXISTS PROD_PLATINUM;

GRANT USAGE, CREATE SCHEMA ON DATABASE PROD_LANDING_ADF TO ROLE DBT_PROD_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE PROD_BRONZE_ADF TO ROLE DBT_PROD_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE PROD_SILVER TO ROLE DBT_PROD_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE PROD_GOLD_ADF TO ROLE DBT_PROD_ROLE;
GRANT USAGE, CREATE SCHEMA ON DATABASE PROD_PLATINUM TO ROLE DBT_PROD_ROLE;

CREATE SCHEMA IF NOT EXISTS PROD_LANDING_ADF.AIRBNB;
CREATE SCHEMA IF NOT EXISTS PROD_GOLD_ADF.AIRBNB;

GRANT ALL PRIVILEGES ON SCHEMA PROD_LANDING_ADF.AIRBNB TO ROLE DBT_PROD_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA PROD_GOLD_ADF.AIRBNB TO ROLE DBT_PROD_ROLE;

-- ============================================================================
-- NOTES
-- ============================================================================
-- After creating databases and schemas for each environment, you need to:
-- 1. Create the landing tables (AirBnBListings, AirBnBReviews, AirBnBDrivers)
-- 2. Create the gold dimension tables (DIM_GEOGRAPHY, DIM_GEOGRAPHY_GEOSPATIAL)
-- 3. Insert sample/reference data into the dimension tables
--
-- Use the dev_environment_setup.sql as a template and replace DEV with the
-- appropriate environment prefix.
-- ============================================================================
