name: datahub_refinery
version: 1.0.0
config-version: 2
profile: datahub_refinery
quoting: { identifier: true }

model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
  
models:
  datahub_refinery:
    +persist_docs: { relation: true, columns: true }
    
    bronze_adf:
      +database: "{{ (target.name ~ '_BRONZE_ADF') | upper }}"
      airbnb:
        +materialized: table
        +schema: AIRBNB

    gold:
      +database: "{{ (target.name ~ '_GOLD_ADF') | upper }}"
      +materialized: incremental
      airbnb:
        +schema: AIRBNB

snapshots:
  datahub_refinery:
    +persist_docs: { relation: true, columns: true }

    silver:
      +database: "{{ (target.name ~ '_SILVER_ADF') | upper }}"
      
      airbnb:
        +schema: AIRBNB