datahub_refinery:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: DANDI_DEV_DBT_TRANSFORM
      warehouse: DEV_DANDI_TRANSFORM_WH
      database: DBTCENTRAL
      schema: DBT_ARTIFACTS  # <- set per run
      account: 'wccdwh'
      user: 'SVCDBTDEV'
      # private_key_path: /home/runner/sf_key.p8
      # private_key_passphrase: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PASSPHRASE') }}"
    test:
      type: snowflake
      role: DANDI_TEST_DBT_TRANSFORM
      warehouse: TEST_DANDI_TRANSFORM_WH
      database: DBTCENTRAL
      schema: DBT_ARTIFACTS  # <- set per run
      account: 'wccdwh_test'
      user: 'SVCDBTTEST'
    preprod:
      type: snowflake
      role: DANDI_PREPROD_DBT_TRANSFORM
      warehouse: PREPROD_DANDI_TRANSFORM_WH
      database: DBTCENTRAL
      schema: DBT_ARTIFACTS  # <- set per run
      account: 'wccdwh_preprod'
      user: 'SVCDBTPREPROD'
    prod:
      type: snowflake
      role: DANDI_PROD_DBT_TRANSFORM
      warehouse: PROD_DANDI_TRANSFORM_WH
      database: DBTCENTRAL
      schema: DBT_ARTIFACTS  # <- set per run
      account: 'wccdwh_prod'
      user: 'SVCDBTPROD'
