datahub_refinery:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'YOUR_ACCOUNT_ID') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'YOUR_USERNAME') }}"
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: DEV_BRONZE_ADF
      schema: PUBLIC
      # For local development with password authentication:
      # password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      # For key-pair authentication (recommended for CI/CD):
      authenticator: SNOWFLAKE_JWT
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH', '~/.snowflake/rsa_key.p8') }}"

    test:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'YOUR_ACCOUNT_ID') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'YOUR_USERNAME') }}"
      role: "{{ env_var('SNOWFLAKE_TEST_ROLE', 'DBT_TEST_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TEST_WAREHOUSE', 'DBT_TEST_WH') }}"
      database: TEST_BRONZE_ADF
      schema: PUBLIC
      authenticator: SNOWFLAKE_JWT
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH', '~/.snowflake/rsa_key.p8') }}"

    preprod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'YOUR_ACCOUNT_ID') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'YOUR_USERNAME') }}"
      role: "{{ env_var('SNOWFLAKE_PREPROD_ROLE', 'DBT_PREPROD_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_PREPROD_WAREHOUSE', 'DBT_PREPROD_WH') }}"
      database: PREPROD_BRONZE_ADF
      schema: PUBLIC
      authenticator: SNOWFLAKE_JWT
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH', '~/.snowflake/rsa_key.p8') }}"

    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'YOUR_ACCOUNT_ID') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'YOUR_USERNAME') }}"
      role: "{{ env_var('SNOWFLAKE_PROD_ROLE', 'DBT_PROD_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_PROD_WAREHOUSE', 'DBT_PROD_WH') }}"
      database: PROD_BRONZE_ADF
      schema: PUBLIC
      authenticator: SNOWFLAKE_JWT
      private_key_path: "{{ env_var('SNOWFLAKE_PRIVATE_KEY_PATH', '~/.snowflake/rsa_key.p8') }}"
